export const NETWORK_REQUEST = 'NETWORK_REQUEST';
export const NETWORK_REQUEST_SUCCESS = 'NETWORK_REQUEST_SUCCESS';
export const NETWORK_LIST_REQUEST = 'NETWORK_LIST_REQUEST';
export const NETWORK_LIST_REQUEST_SUCCESS = 'NETWORK_LIST_REQUEST_SUCCESS';
