export const NETWORK_REQUEST = 'NETWORK_REQUEST';
export const NETWORK_REQUEST_SUCCESS = 'NETWORK_REQUEST_SUCCESS';
export const GET_NETWORK_LIST_REQUEST = 'GET_NETWORK_LIST_REQUEST';
export const GET_NETWORK_LIST_REQUEST_SUCCESS = 'GET_NETWORK_LIST_REQUEST_SUCCESS';
export const GET_AUTH_NETWORK_LIST_REQUEST = 'GET_AUTH_NETWORK_LIST_REQUEST';
export const GET_AUTH_NETWORK_LIST_REQUEST_SUCCESS = 'GET_AUTH_NETWORK_LIST_REQUEST_SUCCESS';