export const GET_BLOCK_LIST_REQUEST = 'GET_BLOCK_LIST_REQUEST';
export const GET_BLOCK_LIST_REQUEST_SUCCESS = 'GET_BLOCK_LIST_REQUEST_SUCCESS';
export const GET_BLOCK_DETAILS_REQUEST = 'GET_BLOCK_DETAILS_REQUEST';
export const GET_BLOCK_DETAILS_REQUEST_SUCCESS = 'GET_BLOCK_DETAILS_REQUEST_SUCCESS';