export const GET_CURRENT_CHANNEL_REQUEST = 'GET_CURRENT_CHANNEL_REQUEST';
export const GET_CURRENT_CHANNEL_REQUEST_SUCCESS = 'GET_CURRENT_CHANNEL_REQUEST_SUCCESS';
export const GET_CHANNEL_LIST_REQUEST = 'GET_CHANNEL_LIST_REQUEST';
export const GET_CHANNEL_LIST_REQUEST_SUCCESS = 'GET_CHANNEL_LIST_REQUEST_SUCCESS';
export const CHANGE_CHANNEL_REQUEST = 'CHANGE_CHANNEL_REQUEST';
export const CHANGE_CHANNEL_REQUEST_SUCCESS = 'CHANGE_CHANNEL_REQUEST_SUCCESS';
